### ISSUE TITLE
offering download and upload of scenes and tokens

### ISSUE THREAD

**Issue by Lukas-Sander** [samcf/ogres#117]
I would love to see the option to download and re-upload scenes and tokens. Not just for taking them with you when switching to other devices, but also for managing collections of scenes and such.

Could it be as easy as dumping the indexedDB into a text file, which could be imported at a later point?

Unfortunately I am unfamiliar with clojure, so I can't offer much help in coding.

**Comment by samcf** [comment]
Thanks for the comment! It would be great to be able to move the data around to another device. This isn't a high priority for me at the moment since this app values quickly setting up and tearing down scenes more than as a persistent campaign manager.

Theoretically if you dump the `app` and `images` tables you could re-import them with a script and it should just work.

**Comment by samcf** [comment]
Exporting data and images to a file is now a supported feature (#136) and will be available in the next published release! Thanks @mjhale!
