### ISSUE TITLE
Cannot restore V0.1.31 backup to V0.1.32 web client

### ISSUE THREAD

**Issue by keithhir** [samcf/ogres#156]
A local map was created using V0.1.31 and saved as a backup.  After upgrading the web client to use V0.1.32, restoring from the backup map reverts the change back to V0.1.31.

**Comment by samcf** [comment]
@keithhir unfortunately backups will always send you back to the version they were created in - this is intentional to preserve the user's work despite what changes are made to the project. A lot of the underlying data model was changed in 0.1.32 so its just not compatible with the previous version.

You can continue to work and play in 0.1.31 though - it will always be there!
